:PROPERTIES:
:header-args: :results verbatim :exports both
:END:
#+title: its-jointprobability
#+EXPORT_EXCLUDE_TAGS: noexport

A Bayesian approach to generating metadata for educational materials.

This project is primarily intended to be used as a microservice through the ~nix~ package. Additionally, it includes some CLI utilities in order to (re-) train the model for some data (data not included).

* Utils :oexport:
#+name: format-json
#+begin_src shell sh :var result="" :results verbatim
echo $result | json
#+end_src

#+name: format-prediction
#+begin_src python :var result="" :results verbatim output :session python-jointprobability-demo
import json
import pandas as pd
result_dict = json.loads(result)["predictions"]
for key, value in result_dict.items():
    print(key)
    print("--------------------------------------------------------------------")
    df = pd.DataFrame.from_dict(value).set_index("name")
    df = df.drop("id", axis=1)
    df["prob_interval"] = df.apply(lambda x: [f"{y:g}" for y in x["prob_interval"]], axis=1)
    print(df)
    print()
#+end_src

* Usage

** Service

With ~Nix~, no further installation is required to run the microservice. Simply run the following command:
#+begin_src shell
nix run github:openeduhub/its-jointprobability
#+end_src
or optionally, with CUDA support:
#+begin_src shell
nix run "github:openeduhub/its-jointprobability#with-cuda"
#+end_src

If the package has been installed locally, the service is also available as ~its-jointprobability~ from the command line.

For more information on configuration options, see
#+begin_src shell
nix run github:openeduhub/its-jointprobability -- --help
#+end_src

Once started, see the ~Swagger~ UI for documentation on the service.
It is located on =http://localhost:8080/docs= by default.

** Model Training

To retrain the model under some data, use the included ~retrain-model~ CLI tool, e.g. through
#+begin_src shell
nix run "github:openeduhub/its-jointprobability#retrain-model" -- <path/to/data-dir>
#+end_src
or, *highly recommended*, with CUDA:
#+begin_src shell
nix run "github:openeduhub/its-jointprobability#retrain-model-with-cuda" -- <path/to/data-dir>
#+end_src

The utility will look for =train_data= and =train_labels=, which are assumed to files that can be loaded through [[https://pytorch.org/docs/stable/generated/torch.load.html][torch.load]]. These should be (=float=-type) [[https://pytorch.org/docs/stable/tensors.html#torch.Tensor][torch.Tensor]] objects with the following content:
- ~train_data_labeled~ :: a two-dimensional =Tensor= where the first dimension corresponds to the individual documents to use for training and the second dimensions contains each document's content, encoded through their Bag-of-words representation.
- ~train_targets~ :: a two-dimensional =Tensor= where the first dimension corresponds to the individual documents to use for training and the second dimension encodes whether each document belongs to each discipline (=1.0= if it does, =0.0= otherwise).

Once the data has been loaded, the topic model will be trained (this will take a long time) and saved within the set directory under =prodslda=. If this file already exists, this step is skipped.

Finally, the Bayesian classification model is trained and saved under =classification=. At this point, some quality metrics will be computed for the model on the training data. If ~test_data_labeled~ and ~test_targets~ are present in the given directory (analogous to the training data), these quality metrics will also be computed for this testing data.

* Features & Demo of the Service
:PROPERTIES:
:header-args: :results verbatim :exports both :post format-json(result=*this*) :wrap src
:END:

** Ping

Once the service has started, we can ping it to check that it is responding to requests:
#+begin_src shell :post :exports both
curl -i -X GET http://localhost:8080/_ping
#+end_src

#+RESULTS:
#+begin_src
HTTP/1.1 200 OK
date: Mon, 15 Jan 2024 15:34:05 GMT
server: uvicorn
content-length: 4
content-type: application/json

null
#+end_src

** Discipline Prediction
:PROPERTIES:
:header-args: :results verbatim :exports both :post format-prediction(result=*this*) :wrap src
:END:

With the =/predict= endpoint, we can send a text to the model. For readability, we only ask for the seven most relevant categories for each metadata field.

In addition to the identifiers of the predicted metadata, we also get some diagnostics that help us understand whether this is a relevant match (in principle, all categories are always returned). Specifically, we gain two point-estimates (mean and median) for the probability of the category belonging to the given text, according to the model. We also get a credibility interval (by default 80%) on said probability.

In the example below, we get only one relevant school discipline, which is also the one we would be expecting for the text (Mathematics). Because the text is relatively short, the probability of this fit is still relatively low. We also get a strong match with Sekundarstufe I, which is also what we would expect, given that Pythagoras' Theorem is usually covered in early High School.
#+begin_src shell :exports both
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'Content-Type: application/json' \
  -d '{
  "text": "Der Satz des Pythagoras lautet: a^2 + b^2 = c^2. Er wird benutzt, um die Hypotenuse eines rechtwinkligen Dreiecks zu berechnen.",
  "num_predictions": "7"
}'
#+end_src

#+RESULTS:
#+begin_src
properties.ccm:educationalcontext
--------------------------------------------------------------------
                    mean_prob  median_prob          prob_interval
name                                                             
Sekundarstufe I      0.658021     0.699045     [0.474334, 0.9088]
Sekundarstufe II     0.499472     0.499016   [0.241794, 0.754773]
Primarstufe          0.289530     0.261378  [0.0701408, 0.432231]
Erwachsenenbildung   0.241155     0.198950  [0.0450375, 0.393112]
Berufliche Bildung   0.231888     0.191726  [0.0328422, 0.316945]
Hochschule           0.212497     0.167900  [0.0417818, 0.358852]
Förderschule         0.207525     0.167493    [0.03359, 0.312417]

properties.ccm:educationalintendedenduserrole
--------------------------------------------------------------------
            mean_prob  median_prob           prob_interval
name                                                      
Lerner/in    0.828479     0.870024    [0.748927, 0.982406]
Lehrer/in    0.794146     0.845071    [0.656783, 0.948103]
Eltern       0.252709     0.232374   [0.0273485, 0.368754]
Berater/in   0.202883     0.177807   [0.0233867, 0.329185]
andere       0.192102     0.154605   [0.0223901, 0.315114]
Autor/in     0.184069     0.153056   [0.0247242, 0.277758]
Verwaltung   0.182313     0.150311  [0.00864722, 0.284704]

properties.ccm:taxonid
--------------------------------------------------------------------
                          mean_prob  median_prob          prob_interval
name                                                                   
Mathematik                 0.521429     0.521309    [0.302945, 0.77839]
Englisch                   0.253041     0.208309     [0.0427305, 0.446]
Chemie                     0.217941     0.196143  [0.0305108, 0.339543]
Deutsch als Zweitsprache   0.237192     0.192009   [0.031477, 0.350231]
Biologie                   0.238565     0.187218  [0.0457654, 0.397943]
Französisch                0.220683     0.183951  [0.0704839, 0.365737]
Geschichte                 0.202717     0.178467  [0.0232776, 0.301736]
#+end_src

Note that these predictions are stochastic, so another run on the same text may yield slightly different predictions:
#+begin_src shell :exports both
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'Content-Type: application/json' \
  -d '{
  "text": "Der Satz des Pythagoras lautet: a^2 + b^2 = c^2. Er wird benutzt, um die Hypotenuse eines rechtwinkligen Dreiecks zu berechnen.",
  "num_predictions": "7"
}'
#+end_src

#+RESULTS:
#+begin_src
properties.ccm:educationalcontext
--------------------------------------------------------------------
                    mean_prob  median_prob          prob_interval
name                                                             
Sekundarstufe I      0.665222     0.703440   [0.481953, 0.904382]
Sekundarstufe II     0.499401     0.491310   [0.254192, 0.783548]
Primarstufe          0.274698     0.224724   [0.0612927, 0.40202]
Erwachsenenbildung   0.244384     0.219650   [0.084634, 0.406045]
Hochschule           0.223554     0.203869   [0.014051, 0.346356]
Berufliche Bildung   0.240852     0.200625  [0.0455448, 0.394151]
Förderschule         0.197599     0.164594    [0.037679, 0.33272]

properties.ccm:educationalintendedenduserrole
--------------------------------------------------------------------
            mean_prob  median_prob          prob_interval
name                                                     
Lerner/in    0.823896     0.856684    [0.721213, 0.95973]
Lehrer/in    0.782832     0.812762   [0.668938, 0.945376]
Berater/in   0.224046     0.195050  [0.0463282, 0.353582]
Eltern       0.239064     0.194380  [0.0423679, 0.373016]
Autor/in     0.203124     0.161245  [0.0418188, 0.313452]
Verwaltung   0.187819     0.153552  [0.0192696, 0.276231]
andere       0.193596     0.132355  [0.0250736, 0.331321]

properties.ccm:taxonid
--------------------------------------------------------------------
                          mean_prob  median_prob          prob_interval
name                                                                   
Mathematik                 0.499852     0.510836   [0.167055, 0.738145]
Chemie                     0.252636     0.220809  [0.0371943, 0.405137]
Deutsch                    0.217688     0.193759  [0.0525608, 0.338934]
Physik                     0.227868     0.186849  [0.0403695, 0.374115]
Französisch                0.205184     0.185719  [0.0483919, 0.314607]
Allgemein                  0.218597     0.185465  [0.0486199, 0.348236]
Deutsch als Zweitsprache   0.223251     0.184693   [0.0186659, 0.31266]
#+end_src

To reduce this variance, we can increase the number of samples being drawn for the prediction. Note that the computation time is proportional to the number of such samples. By default, 100 samples are drawn.
#+begin_src shell :exports both
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'Content-Type: application/json' \
  -d '{
  "text": "Der Satz des Pythagoras lautet: a^2 + b^2 = c^2. Er wird benutzt, um die Hypotenuse eines rechtwinkligen Dreiecks zu berechnen.",
  "num_predictions": "7",
  "num_samples": "1000"
}'
#+end_src

#+RESULTS:
#+begin_src
properties.ccm:educationalcontext
--------------------------------------------------------------------
                    mean_prob  median_prob          prob_interval
name                                                             
Sekundarstufe I      0.650441     0.674349   [0.481981, 0.938495]
Sekundarstufe II     0.516556     0.520473   [0.252717, 0.761069]
Primarstufe          0.278886     0.253224  [0.0498418, 0.429445]
Erwachsenenbildung   0.249482     0.211876   [0.0285058, 0.38824]
Berufliche Bildung   0.221897     0.188808  [0.0253961, 0.340086]
Hochschule           0.198004     0.163731  [0.0312252, 0.314725]
Förderschule         0.201567     0.163656  [0.0284056, 0.310227]

properties.ccm:educationalintendedenduserrole
--------------------------------------------------------------------
            mean_prob  median_prob          prob_interval
name                                                     
Lerner/in    0.808085     0.841381   [0.705179, 0.977149]
Lehrer/in    0.766023     0.806606   [0.637527, 0.973092]
Eltern       0.239753     0.211442  [0.0295855, 0.373897]
Berater/in   0.218313     0.180937  [0.0241492, 0.338786]
Verwaltung   0.183099     0.151989  [0.0195939, 0.284953]
Autor/in     0.181802     0.144597  [0.0202414, 0.281662]
andere       0.179169     0.140996  [0.0265931, 0.295452]

properties.ccm:taxonid
--------------------------------------------------------------------
                          mean_prob  median_prob          prob_interval
name                                                                   
Mathematik                 0.505273     0.504157   [0.262459, 0.784126]
Deutsch als Zweitsprache   0.233756     0.208840  [0.0291864, 0.365771]
Chemie                     0.235958     0.199171  [0.0397885, 0.370252]
Englisch                   0.220629     0.184711  [0.0274543, 0.345064]
Medienbildung              0.213993     0.183739  [0.0344219, 0.334567]
Deutsch                    0.216800     0.174964  [0.0364801, 0.344951]
Physik                     0.206465     0.167167   [0.025051, 0.317184]
#+end_src

Second run, for comparison
#+begin_src shell :exports both
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'Content-Type: application/json' \
  -d '{
  "text": "Der Satz des Pythagoras lautet: a^2 + b^2 = c^2. Er wird benutzt, um die Hypotenuse eines rechtwinkligen Dreiecks zu berechnen.",
  "num_predictions": "7",
  "num_samples": "1000"
}'
#+end_src

#+RESULTS:
#+begin_src
properties.ccm:educationalcontext
--------------------------------------------------------------------
                    mean_prob  median_prob          prob_interval
name                                                             
Sekundarstufe I      0.649309     0.670549   [0.453869, 0.893656]
Sekundarstufe II     0.530846     0.537787   [0.241456, 0.770304]
Primarstufe          0.270643     0.232525  [0.0546212, 0.419813]
Erwachsenenbildung   0.241038     0.209709  [0.0321171, 0.366913]
Berufliche Bildung   0.222027     0.190116    [0.023952, 0.33548]
Hochschule           0.199722     0.167652  [0.0228731, 0.300193]
Förderschule         0.203787     0.165810  [0.0251269, 0.312907]

properties.ccm:educationalintendedenduserrole
--------------------------------------------------------------------
            mean_prob  median_prob          prob_interval
name                                                     
Lerner/in    0.816782     0.844739   [0.720125, 0.981454]
Lehrer/in    0.770526     0.805283   [0.651358, 0.971309]
Eltern       0.223892     0.191749  [0.0388262, 0.351971]
Berater/in   0.203746     0.166421  [0.0277933, 0.309196]
Verwaltung   0.182778     0.151235  [0.0279511, 0.280854]
andere       0.174801     0.147197   [0.024438, 0.276108]
Autor/in     0.176841     0.141992  [0.0289599, 0.282311]

properties.ccm:taxonid
--------------------------------------------------------------------
                          mean_prob  median_prob          prob_interval
name                                                                   
Mathematik                 0.493860     0.495209    [0.20909, 0.776847]
Chemie                     0.235152     0.202340  [0.0319766, 0.356456]
Englisch                   0.227078     0.194947   [0.0362673, 0.35393]
Deutsch                    0.225882     0.193521  [0.0339627, 0.348184]
Deutsch als Zweitsprache   0.233946     0.192438  [0.0278407, 0.372269]
Französisch                0.211606     0.178255   [0.0331905, 0.33729]
Biologie                   0.203784     0.172051  [0.0258666, 0.321914]
#+end_src

Note that the individual probabilities of the categories do not add up to 1. This is intended, as assigning a text multiple relevant categories is often desired. As an example, take the following paragraph taken from [[https://de.wikipedia.org/wiki/Deutschland][the German Wikipedia page on Germany]]. This is mostly about the history of Germany, but because it also covers relatively recent developments, it may also be relevant to politics.
#+begin_src shell :exports both
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'Content-Type: application/json' \
  -d '{
  "text": "Die rasche Entwicklung vom Agrar- zum Industriestaat vollzog sich während der Gründerzeit in der zweiten Hälfte des 19. Jahrhunderts. Nach dem Ersten Weltkrieg wurde 1918 die Monarchie abgeschafft und die demokratische Weimarer Republik konstituiert. Ab 1933 führte die nationalsozialistische Diktatur zu politischer und rassistischer Verfolgung und gipfelte in der Ermordung von sechs Millionen Juden und Angehörigen anderer Minderheiten wie Sinti und Roma. Der vom NS-Staat 1939 begonnene Zweite Weltkrieg endete 1945 mit der Niederlage der Achsenmächte. Das von den Siegermächten besetzte Land wurde 1949 geteilt, nachdem bereits 1945 seine Ostgebiete teils unter polnische, teils sowjetische Verwaltungshoheit gestellt worden waren. Der Gründung der Bundesrepublik als demokratischer westdeutscher Teilstaat mit Westbindung am 23. Mai 1949 folgte die Gründung der sozialistischen DDR am 7. Oktober 1949 als ostdeutscher Teilstaat unter sowjetischer Hegemonie. Die innerdeutsche Grenze war nach dem Berliner Mauerbau (ab 13. August 1961) abgeriegelt. Nach der friedlichen Revolution in der DDR 1989 erfolgte die Lösung der deutschen Frage durch die Wiedervereinigung beider Landesteile am 3. Oktober 1990, womit auch die Außengrenzen Deutschlands als endgültig anerkannt wurden. Durch den Beitritt der fünf ostdeutschen Länder sowie die Wiedervereinigung von Ost- und West-Berlin zur heutigen Bundeshauptstadt zählt die Bundesrepublik Deutschland seit 1990 sechzehn Bundesländer.",
  "num_predictions": "7",
  "num_samples": "1000"
}'
#+end_src

#+RESULTS:
#+begin_src
properties.ccm:educationalcontext
--------------------------------------------------------------------
                    mean_prob  median_prob          prob_interval
name                                                             
Sekundarstufe I      0.816749     0.848090    [0.705954, 0.97302]
Sekundarstufe II     0.513776     0.520729   [0.260114, 0.771751]
Elementarbereich     0.188629     0.157278  [0.0182773, 0.286166]
Hochschule           0.189579     0.153754  [0.0253105, 0.296105]
Erwachsenenbildung   0.189638     0.149587  [0.0197636, 0.281026]
Fortbildung          0.179133     0.145827  [0.0252319, 0.285525]
Fernunterricht       0.172680     0.137081  [0.0144026, 0.261526]

properties.ccm:educationalintendedenduserrole
--------------------------------------------------------------------
            mean_prob  median_prob           prob_interval
name                                                      
Lehrer/in    0.810410     0.845959     [0.70685, 0.976241]
Lerner/in    0.724129     0.752912    [0.569461, 0.953618]
Eltern       0.185150     0.155580   [0.0184804, 0.281891]
andere       0.185800     0.149270   [0.0172502, 0.291646]
Berater/in   0.185574     0.147028   [0.0173999, 0.286302]
Autor/in     0.181543     0.145211    [0.025134, 0.285407]
Verwaltung   0.154631     0.120897  [0.00918061, 0.234378]

properties.ccm:taxonid
--------------------------------------------------------------------
            mean_prob  median_prob          prob_interval
name                                                     
Geschichte   0.793975     0.824977    [0.68321, 0.979403]
Politik      0.276390     0.246461  [0.0481908, 0.425796]
Physik       0.255998     0.222310  [0.0327929, 0.387161]
Religion     0.207240     0.171416  [0.0208709, 0.326707]
Deutsch      0.205695     0.169456  [0.0267181, 0.317204]
Pädagogik    0.196383     0.160055  [0.0179781, 0.316849]
Ethik        0.192309     0.159001   [0.0210824, 0.29595]
#+end_src

* Notes / Limitations

** RAM Usage
The service requires roughly 2GB of RAM to operate. This usage should be static with time.

** Cutoffs
Because of the nature of the model, it can be difficult to decide on which predictions shall be counted as actually being predicted to be assigned. Experimentally, a cutoff of around 0.25 for the mean probability for the school discipline and 0.3 for the educational context appear to be good metrics.

However, more investigations into better cutoffs, e.g. per-category, might be useful.

* Installation (through ~Nix Flakes~)

Add this repository to your Flake inputs. This may look like this:
#+begin_src nix
{
  inputs = {
    its-jointprobability = {
      url = "github:openeduhub/its-jointprobability";
      # optional if using as application, required if using as library
      nixpkgs.follows = "nixpkgs"; 
    };
  };
}
#+end_src

The micro-service is provided both as a ~nixpkgs~ overlay and as an output (~packages.${system}.its-jointprobability~). Thus, it may be included through
#+begin_src nix
{
  outputs = { self, nixpkgs, its-jointprobability, ... }:
    let
      system = "x86_64-linux";
      pkgs =
        (nixpkgs.legacyPackages.${system}.extend
          its-jointprobability.overlays.default);
    in
    { ... };
}
  
#+end_src

The Python library is provided as an output (~lib.${system}.its-jointprobability~). Note that this is a function mapping a Python package (e.g. ~pkgs.python310~) to the library. Its inclusion may look like this:
#+begin_src nix
{
  outputs = { self, nixpkgs, its-jointprobability, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      
      python-with-packages =
        pkgs.python310.withPackages (py-pkgs: [
          # some example packages
          py-pkgs.numpy
          py-pkgs.pandas
          # the its-jointprobability library
          (its-jointprobability.lib.${system}.its-jointprobability py-pkgs)
        ]);
    in
    { ... };
}
#+end_src
